# Site Settings
title: Rick Venutolo
email: rick@example.com
description: >
  Senior Code Monkey from Atlanta, GA
baseurl: ""
url: "http://localhost:4000"
twitter_username: rick_venutolo
github_username:  rvenutolo

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
